[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lrbwhite", email = "3523395067@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
